apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: chatbot-m1742482938849
  janus-idp.io/tekton: chatbot-m1742482938849
  backstage.io/kubernetes-id: chatbot-m1742482938849
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: chatbot-m1742482938849
resources:
  - application-dev.yaml
