apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: chatbot-m1742482938849
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-m1742482938849
  name: chatbot-m1742482938849
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
